### ISSUE TITLE
Readme Need Update

### ISSUE THREAD

**Issue by anisharaz** [Ryrahul/Video-Streaming#1]
- the cloning command is using ssh which doesn't allow other users , change it to http clone command.
- the pnpm to install and npm to start doesn't feel intuative , making it npm or pnpm would be better.

**Comment by Ryrahul** [comment]
Addressed in the following commit . Used Nest CLI to generate which caused the following issue  [#c858b3e](https://github.com/Ryrahul/Video-Streaming/commit/c858b3e9857492a204fcfd5bbff348b34c1d72a6).
